### ISSUE TITLE
fail to request PHP

### ISSUE THREAD

**Issue by ankurhora** [InMobi/api-monetization#2]
Hi, 
i am using your api in PHP having problem processing the request.

It says "Please provide a valid Device in the request"

This is what i found in the request/Strubs.php Device class

class Device {
    /**
     * 
     * The String value containing the carrier IP. Must be a valid carrier IP ,of the device.
     */
    public $carrierIP ;
    /**
    * The Browser/WebView User Agent String of the device. Must not be empty.
    **/
    public $userAgent ;
    /**
    * The Google Play advertising identifier as obtained from the device.
    **/
    public $gpId ;
    /**
    * The The ANDROID_ID value of the device, must be passed as SHA-1 or MD5 hashed value.
    **/
    public $androidId ;
    /**
    * The Apple advertising identifier value, for the device.
    **/
    public $idfa ;
    /**
    * The Geo, as set for this instance.
    **/
    public $geo ;

    /**
    * iOS
    * This parameter is used only for iOS 6, and above, devices. It indicates if Limit Ad Tracking is enabled or disabled by the user. The values of this can be: Yes (1) or No (0).
    * Android
    * This parameter indicates whether the user wants to opt out of Interest based Ads, and can be enabled or disabled by user. The values of this can be: Yes (1) or No (0). 
    * More information about this is present here.
    * Note: Although this is not a mandatory parameter, it is important for adhering to policies regarding user opt-out, and to address user privacy concerns.
    **/
    public $adTrackingDisabled;

    function __construct($carrierIP,$userAgent) {

        $carrierIP = $carrierIP;
        $userAgent = $userAgent;
        $gpId = null;
        $androidId = null;
        $idfa = null;
        $geo = null;
        $adTrackingDisabled = false;
     } 

     /**
     * Use this method to check if this Object has all the required parameters
     * present, to be used to construct a JSON request. The required parameters
     * would be specific to an ad-format.
     * 
     * @return If the mandatory params are present, then true, otherwise false.
     */
     public function isValid() {
        
        if(StubValidator::isStringValid($this->carrierIP) == false) return false; 
        if(StubValidator::isStringValid($this->userAgent) == false) return false;
        //put checks for device id later on..
        return true;
     }
} 

Isn't the constructor should be : 
function __construct($carrierIP,$userAgent) {

        $this->carrierIP = $carrierIP;
        $this->userAgent = $userAgent;
        $this->gpId = null;
        $this->androidId = null;
        $this->idfa = null;
        $this->geo = null;
        $this->adTrackingDisabled = false;
     }

**Comment by rish2cool** [comment]
Hi Ankur, Can you raise a pull request with the changes?

**Comment by rish2cool** [comment]
Made the required changes here in Stubs classes
