### ISSUE TITLE
Invalid impression error Impression 

### ISSUE THREAD

**Issue by ankurhora** [InMobi/api-monetization#3]
The impression class goes like this 

class Impression {
    public $noOfAds = 1;
    protected $isInterstitial = false;
    public $displayManager = "s_imapi_php";
    public $displayManagerVersion = "1.0.0";
    public $slot;

    function __construct($s) {
        $slot = $s;
    }
    static function getImpressionObjectWithSlot($s) {
        $imp = new Impression();
        $imp->slot = $s;
        return $imp;
    }
    public function isValid() {
        //only check if slot is valid here..
        if($this->slot == null) return false;
        if(gettype($this->slot) != "object") return false;
        return $this->slot->isValid();
    }
}

Through constructor the slot is not set properly which throws an error of "Please provide a valid Impression in the request"

The constructor function should go like this : 
 function __construct($s) {
        $this->slot = $s;
    }

**Comment by rish2cool** [comment]
Made the required changes in the class.
