### ISSUE TITLE
Trying to get property of non-object USER in JSONPayloadCreator.php

### ISSUE THREAD

**Issue by ankurhora** [InMobi/api-monetization#4]
JSONPayloadCreator throws an error "Trying to get property of non-object"
private static function getUserJson($user) {
		//TODO Data object implementation
		$userArray = array();
		$yob = $user->yearOfBirth; 
		
		if(StubValidator::isIntegerValid($yob) && $yob > 0) {                 // here 
			$userArray['yob'] = $yob;
		}
		$gender = $user->gender;
		if($gender != null) {
			if($gender == Gender::MALE) {
				$userArray['gender'] = 'M';
			} else if($gender == Gender::FEMALE) {
				$userArray['gender'] = 'F';
			}
		}
		return $userArray;
	}

Since the user information is optional in the request so, if the user is not set in the request this code doesnt work.

**Comment by rish2cool** [comment]
I've corrected this, please check once.
