### ISSUE TITLE
POST Request to the APi

### ISSUE THREAD

**Issue by ankurhora** [InMobi/api-monetization#8]
In RequestResponseManager.php

if($requestJson != null && empty($requestJson) != true) {
            //fire the http request
            $ch = curl_init();
            //set the url, number of POST vars, POST data
            curl_setopt($ch,CURLOPT_URL,"http://api.w.inmobi.com/showad/v2.1");
            //curl_setopt($ch,CURLOPT_POST, 1);                                              //here
            curl_setopt($ch,CURLOPT_POSTFIELDS, $requestJson);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                                            'Content-Type: application/json'
                                            ,'x-device-user-agent:'.$userAgent
                                            ,'x-forwarded-for:'.$carrierIP
                                            ));
            //execute post
            $result = curl_exec($ch);
            //close connection
            $httpStatusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

should this line "//curl_setopt($ch,CURLOPT_POST, 1);     " be uncommented as it requires to send a post request to the api?

**Comment by rishabh-chowdhary** [comment]
sorry my laptop got formatted, but when I had tested earlier the POST request was working for me without the flag..? Is it not working for you?
